### ISSUE TITLE
No SAML Settings are displayed when Teamcity is configured for a custom context

### ISSUE THREAD

**Issue by sm97** [morincer/teamcity-plugin-saml#51]
![image](https://user-images.githubusercontent.com/9654317/89896748-a840c700-dbe6-11ea-9a17-e4ad91b1b9c8.png)
catalina.out: https://gist.github.com/sm97/d21f0ad51c0e58c08598a11b799c2d98

**Comment by morincer** [comment]
Hi! Usually it means some troubles with JS. Would you please check if JS console in browser shows some errors?

**Comment by sm97** [comment]
My Teamcity installation uses /teamcity context (Server URL: https://example.com/teamcity/) while your plugin does not use it.

`  
    

<div id=app></div>
<script src="/plugins/saml-authentication/admin-ui/js/app.js"></script>

  `

**Comment by morincer** [comment]
Ok, confirm. Internally the plugin is getting the path using TC-provided SDK and it seems that the SDK method doesn't honor custom context. Will check for possible workaround.

**Comment by morincer** [comment]
Fixed.

**Comment by sm97** [comment]
@morincer Thanks alot. Unfortunatly I cannot rebuild updated version of this plugin. It fails while installing npm dependencies :(
Could you please make a build for me?

**Comment by morincer** [comment]
Sure, grab release releases/tag/1.2.2

**Comment by sm97** [comment]
@morincer Thanks again. I got it and SAML configuration page is not empty now.
Though not all links are still functioning.
For example, /app/saml/metadata.xml still does not use context :(

**Comment by morincer** [comment]
Ok, I'll check it

**Comment by morincer** [comment]
Ok, give then new version (1.3) a try.

**Comment by sm97** [comment]
@morincer Could you please build this version to test?

**Comment by morincer** [comment]
Fixed in 1.3.1

**Comment by sm97** [comment]
Good job. Thank you! It works like a charm :)
